### ISSUE TITLE
Perhaps adding † functionality?

### ISSUE THREAD

**Issue by navidcy** [musm/EasyTranspose.jl#1]

**Comment by musm** [comment]
You want to use  †  instead of  ᵀ   for transpose? 

I think that's confusing since  † is typically used to denote the Hermitian tranpose.

**Comment by navidcy** [comment]
Sorry, I should have elaborated more.
I was just proposing to add an **extra** functionality that does transpose+conjugate using the † symbol.

**Comment by musm** [comment]
So you want to also add  ` †` to do Hermitian transpose, which you can already do using `'` ?

**Comment by navidcy** [comment]
Yes, but `'` gives back a different type:

```julia
julia> A = rand(3, 3) + im*rand(3, 3);

julia> typeof((A)ᵀ)
Array{Complex{Float64},2}

julia> typeof(A')
LinearAlgebra.Adjoint{Complex{Float64},Array{Complex{Float64},2}}
```

I was suggesting something along the lines of
```julia
julia> typeof((A)†)
Array{Complex{Float64},2}
```

Wouldn't this be useful? Perhaps it's redundant.

**Comment by musm** [comment]
Not very useful since that kind of defeats the purpose of the wrapper which is meant to avoid copies.

In any case we can't  use `†` yet since it's not recognized in Julia as an identifier.
